### ISSUE TITLE
Requests - No User Agent

### ISSUE THREAD

**Issue by artdude543** [WatchBeam/beam-client-node#11]
In theory this module _should_ be sending a user agent with any requests. As CloudFlare can / will stop requests with no agents. This would prevent issues like it from happening. I would PR the fix but not sure on what Agent you would like to use. I.E. Custom named for tracking / debugging etc...

**Comment by connor4312** [comment]
Fixed in d18c3f3c6ab07a79024adf6654326b8b53a08b55

**Comment by artdude543** [comment]
Thank you! :)
