### ISSUE TITLE
OAuth Question

### ISSUE THREAD

**Issue by natasha-tullos** [WatchBeam/beam-client-node#114]
I'm currently using your API to test out some OAuth - 

`/oauth/shortcode/check/{handle}`

I'm using the following api endpoint that is referenced in the reference section of your documentation and it says that I should be receiving a code in the response but all I'm getting is a url with this endpoint and the code to get an accessToken in that url - 

I tried adding my clientId to the header as well as the clientSecret but I'm running in circles and haven't been having the best time reading the documentation. 

Am I supposed to get the code through that url somehow? Thanks.

**Comment by ProbablePrime** [comment]
Hey, by reference section are you referring to this page: https://dev.mixer.com/reference/oauth/shortcodeauth

If so are you following steps 1 and 2 listed here before polling the check endpoint?

**Comment by natasha-tullos** [comment]
Hey @ProbablePrime,

I followed 1 and 2 to get the code, yes - but my issue is that I need an access token because I'm experimenting with connecting mixer to firebase to see if I can view my email and such when I authenticate with firebase in my listed users section. For that purpose, I had to start using the endpoints like `mixer.com/api/v1/oauth/shortcode/check/{handle}`

**Comment by ProbablePrime** [comment]
Yup, if you follow those steps you should end up with an access token.

When calling shortcode/check do you have an active handle?

**Comment by natasha-tullos** [comment]
I do have an active handle - the issue is my response on the server where I would hopefully see a code but I don't see one in the response - for reference, I'm using express to make API calls on the server side right now.

![Screen Shot 2020-01-16 at 3 04 26 PM](https://user-images.githubusercontent.com/30872051/72562663-8ad69500-3871-11ea-9230-9e8f1a897e29.png)

**Comment by ProbablePrime** [comment]
What's the body of the request pictured?

**Comment by natasha-tullos** [comment]
The body? It's a get request - I'm just sending my client-id as a header like the following -
`
await fetch('https://mixer.com/api/v1/oauth/shortcode/check/${handle}', { method: 'get',
      headers: {
        'client-id': '{client-id here}',
      }
`

**Comment by ProbablePrime** [comment]
Yes, when the get request returns from our servers it'll have a response body. What is contained in that.

**Comment by natasha-tullos** [comment]
The above image is the response I'm getting on the server side.
On the client side, I'm just getting `{ size: 0, timeout: 0 }` when I try to return the response from the server stored as a variable.

**Comment by ProbablePrime** [comment]
None of that looks like a response to me unfortunately.

**Comment by natasha-tullos** [comment]
Hmm.. Could it be possible that I'm doing something wrong with how I'm sending the client id in the headers? Or that I might have the wrong API link?

**Comment by ProbablePrime** [comment]
It could be your request handler, how are you listening for the response and what request module are you using?

**Comment by natasha-tullos** [comment]
```
let checkForAuth = async (handle) => {
  let loading = true;
  let result;

  while (loading) {
    await fetch('https://mixer.com/api/v1/oauth/shortcode/check/${handle}', { method: 'get',
      headers: {
        'client-id': '{client-id}'
      }
   })
      .then(res => {
        if (res.status !== 200) {
          loading = true;
        } else {
          loading = false;
          result = res;
        }
      })
      .catch(err => console.log(err))
  }

  return result;
}
```


This is how I'm calling the API and I'm using a while loop as a way of polling until I get the code.

**Comment by ProbablePrime** [comment]
can you console.log(res.body) here:
```js
if (res.status !== 200) {
          loading = true;
        } else {
		//HERE :)
          loading = false;
          result = res;
        }
```

**Comment by natasha-tullos** [comment]
![Screen Shot 2020-01-16 at 3 38 17 PM](https://user-images.githubusercontent.com/30872051/72564819-3e418880-3876-11ea-8b0b-d05923c49432.png)

When I added the console.log and tried again, this is the response I got for the res.body

**Comment by ProbablePrime** [comment]
Oh its fetch i understand now. 

To read the response from your request you need to use res.json() which returns another promise for documentation pelase see: https://www.npmjs.com/package/node-fetch#json

**Comment by natasha-tullos** [comment]
Thank you so much!! That worked - I really appreciate the help. 😄

**Comment by ProbablePrime** [comment]
No worries!
