### ISSUE TITLE
[TypeScript] Third Party Definitions / Official Support

### ISSUE THREAD

**Issue by artdude543** [WatchBeam/beam-client-node#18]
Heyo,

I've been working on creating a [TypeScript definition for this module](https://github.com/ExoZoneDev/typings-beam-client-node) (and the interactive one soon) to help with people using this module with TypeScript. For this I'd like to publish it to the registry and such so it's easily downloadable for users. You can find information about the registry [here](https://github.com/typings/registry#typings-registry) along with how the contribution system works. I do intend to keep the Typings up to date as much as I can along with possible support from the community.

I've come to here to ask for permission to host and create the Typings for this module and `beam-interactive-node` this could either be official or third party depending on how you guys want to handle this.

If you need more information about this or have questions please do ask.

**Comment by UnwrittenFun** [comment]
I think it would be nice having the typings in this repo, I would be happy to help keep it up to date.

What do you think @connor4312?

**Comment by connor4312** [comment]
I'd be cool with having official ts definitions. What do you need from us to make that happen, @artdude543?

**Comment by artdude543** [comment]
Either we can ship the definitions in this repo or use the registry. Either option works but for the registry all I need is a statement from guys allowing me to publish the typings to the registry. Then it's a matter of the definitions being kept up to date which is pretty easy.

It would be nice having the definitions included here, but some developers preferring installing them. Me personally would prefer them being included so save a step but that would require constant PR's of updates to the typings. Which I don't really want to bother you guys with all the time. So maybe the registry would be more ideal for that.

What are your thoughts on it?

**Comment by artdude543** [comment]
I thought about this more and I think it may be easier to use the registry system for now. Unless this module get's a re-write ;) I can see having to make PR's all the time for small changes to the defs become annoying for you developers. Unless you don't really mind?

**Comment by connor4312** [comment]
It's up to @MattJustMatt but I'd be fine giving you commit access on this repo.

**Comment by artdude543** [comment]
Ahh okay I started working on the interactive typings so will also have that soon. Will make a PR to that repo with the typings.

**Comment by artdude543** [comment]
@MattJustMatt any thoughts / concerns about this?

**Comment by artdude543** [comment]
Reopened? Did I miss something, or ya have some questions?

**Comment by connor4312** [comment]
Waiting on a response for the last few comments 😉  Github closes issues automatically when pull requests are merged that contain things like "fixes #18", which is what happened.

**Comment by artdude543** [comment]
Ahh, I did not know that including the words on PR descriptions closed issues. (I thought it was titles and comments only) Well I learned something new xD

**Comment by connor4312** [comment]
Hey @artdude543, for now we're just going to take PRs into this repo. If you do do a significant rewrite as talked about in #24 we'd be up for revisiting this, but the review and merge process works well for now. Thanks again for your contributions! 😄
