### ISSUE TITLE
TypeError: _.defaultsDeep is not a function

### ISSUE THREAD

**Issue by pannous** [WatchBeam/beam-client-node#19]
```
./example/joinChat.js 
/beam-client-node/lib/client.js:109
    var req = _.defaultsDeep(data || {}, _.extend(
                ^

TypeError: _.defaultsDeep is not a function
    at Client.request (/beam-client-node/lib/client.js:109:17)
    at PasswordProvider.attempt (/beam-client-node/lib/providers/password.js:29:24)
    at Object.<anonymous> (/beam-client-node/example/joinChat.js:10:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3

```

**Comment by SimonSchick** [comment]
`defaultsDeep` is available since lodash 3.10.0, this package requires at east 4.0.0.

Are you sure you haven't accidentally overwritten something?
Try `rm -rf node_modules` and `npm i` your project again.

**Comment by SimonSchick** [comment]
Also please post the following information:
- Node/Browser version
- Installed version of `beam-client-node`
- Additionally a copy of the result of `npm ls` from inside your project could be helpful

**Comment by pannous** [comment]
> Try rm -rf node_modules

thanks, that helped**

We just realized though that we have to host our own beam server or wait for the pending partnership approval for this to work, right?

https://github.com/WatchBeam/beam-client-node/tree/master/lib/ws
https://developer.beam.pro/api/chatproto

**
`error joining chat: { [Error: An unknown error occured]
  res: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: 
      { end: [Object],
        close: [Object],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: undefined,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'beam.pro',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: 0,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 145,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: undefined,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'beam.pro',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: 0,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 145,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { server: 'nginx/1.8.1',
        'content-type': 'application/json; charset=utf-8',
        'cache-control': 'no-cache, private',
        'strict-transport-security': 'max-age=31536000',
        via: '1.1 varnish, 1.1 varnish',
        'fastly-debug-digest': '089b70c896138d6995bc716c62eae454a919cf5ba10eae975434caa85e83a5cf',
        'content-length': '78',
        'accept-ranges': 'bytes',
        date: 'Tue, 17 May 2016 11:14:41 GMT',
        age: '0',
        connection: 'close',
        'x-served-by': 'cache-dfw1823-DFW, cache-fra1245-FRA',
        'x-cache': 'MISS, MISS',
        'x-cache-hits': '0, 0',
        'x-timer': 'S1463483681.654287,VS0,VE131',
        vary: 'origin, Accept-Encoding' },
     rawHeaders: 
      [ 'Server',
        'nginx/1.8.1',
        'Content-Type',
        'application/json; charset=utf-8',
        'cache-control',
        'no-cache, private',
        'Strict-Transport-Security',
        'max-age=31536000',
        'Via',
        '1.1 varnish',
        'Fastly-Debug-Digest',
        '089b70c896138d6995bc716c62eae454a919cf5ba10eae975434caa85e83a5cf',
        'Content-Length',
        '78',
        'Accept-Ranges',
        'bytes',
        'Date',
        'Tue, 17 May 2016 11:14:41 GMT',
        'Via',
        '1.1 varnish',
        'Age',
        '0',
        'Connection',
        'close',
        'X-Served-By',
        'cache-dfw1823-DFW, cache-fra1245-FRA',
        'X-Cache',
        'MISS, MISS',
        'X-Cache-Hits',
        '0, 0',
        'X-Timer',
        'S1463483681.654287,VS0,VE131',
        'Vary',
        'origin, Accept-Encoding' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 404,
     statusMessage: 'Not Found',
     client: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: undefined,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'beam.pro',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: 0,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 145,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /api/v1/chats/2 HTTP/1.1\r\nUser-Agent: BeamClient/0.4.0 (JavaScript; Node.js v6.0.0)\r\nhost: beam.pro\r\ncontent-length: 0\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        method: 'GET',
        path: '/api/v1/chats/2',
        parser: null,
        res: [Circular] },
     request: 
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        method: 'get',
        headers: [Object],
        callback: [Function],
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Object],
        _auth: [Object],
        _oauth: [Object],
        _multipart: [Object],
        _redirect: [Object],
        _tunnel: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function],
        uri: [Object],
        proxy: null,
        tunnel: true,
        setHost: true,
        originalCookieHeader: undefined,
        _jar: [Object],
        port: 443,
        host: 'beam.pro',
        path: '/api/v1/chats/2',
        httpModule: [Object],
        agentClass: [Object],
        agent: [Object],
        _started: true,
        href: 'https://beam.pro/api/v1/chats/2',
        req: [Object],
        ntick: true,
        response: [Circular],
        originalHost: 'beam.pro',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body: 
      { message: 'Channel with id 2 not found',
        statusCode: 404,
        error: 'Not Found' } },
  message: 'An unknown error occured' }`

**Comment by SimonSchick** [comment]
Uhh, I don't think there is a channel/chat with id 2.
Please double check your code.

```
simonschick@wizzy-macbook-temp ~ $ curl https://beam.pro/api/v1/channels/2 2>/dev/null | jq
{
  "message": "Channel not found.",
  "statusCode": 404,
  "error": "Not Found"
}
simonschick@wizzy-macbook-temp ~ $ curl https://beam.pro/api/v1/chats/2 2>/dev/null | jq
{
  "message": "Channel with id 2 not found",
  "statusCode": 404,
  "error": "Not Found"
}
```

**Comment by pannous** [comment]
> Please double check your code.

you mean _their_ code;) 
just trying to run their basic example.

**Comment by SimonSchick** [comment]
Oh yea, just noticed, the example references a dead channel, it should fine with another, I'll see to get the example updated.
