### ISSUE TITLE
No handle for ws socket code 1001

### ISSUE THREAD

**Issue by andrejsavikin** [WatchBeam/beam-client-node#22]
It is possible for an application using ws lib provided beam node api to receive ws code 1001. Upon receiving this code, the application is supposed to reconnect to the ws. Beam api however, goes ahead and crashes the whole application instead. Response that is found in the log is: `Error: No handler for reply ID.`.

**Comment by connor4312** [comment]
Can you give a log of what you're seeing over the websocket? Reply IDs are separate from websocket codes.

If you don't attach a handler for the `error` event on the socket, Node will throw error events and result in a crash. It's good practice to always attach to the error event to handle things gracefully.

**Comment by andrejsavikin** [comment]
I can't provide any more info as this is all I'm receiving in the console. Other problem is that this(from my testing) only occurs one per 24hours, so logging all packets would be tedious

**Comment by connor4312** [comment]
I'd recommend adjusting your bot to log everything you can, particularly events sent and received from the websocket. You can then start your bot and redirect the standard input/output to a file. After the bot crashes you can use the `tail` command to view only the last lines of the file, showing you the events that occurred right before its dead.

**Comment by andrejsavikin** [comment]
Alright, this will be implemented into my bot, please expect a response in around 24hours, since that is how long it takes to crash

**Comment by connor4312** [comment]
Thanks!

**Comment by andrejsavikin** [comment]
I just got one, it's a simple packet with just type set to reply and id set to 1001, without any other data. The last sent was a chat message packet that just had the text "Hi!". I can confirm that this packet was recived by beam and that message was displayed in chat

**Comment by connor4312** [comment]
Can you post the raw log you recorded?

**Comment by connor4312** [comment]
Please reopen this with more info if it's still and issue 😄
