### ISSUE TITLE
[TypeScript] Rewrite / Port

### ISSUE THREAD

**Issue by artdude543** [WatchBeam/beam-client-node#24]
Would there be any objects to me creating a PR (When it's completed) of a full TypeScript version of this repo? I'm planning on updating somethings along with converting the code over. I also intend to adding live loading support along with support for the planned socket changes. To get the module ready for that.

If not I could create a fork for people wanting a pure TS module and will post changes here to that. But I'd rather the latter for easier updating / managing / support.

I'd like to use this module more for projects but it's lacking areas such as live loading support along with custom integrations. I'm creating this issue before doing anything to see what your guys thoughts are on this and/or if you already have a planned re-write of this module anytime soon. So I don't end up creating something in which you already have on the sprint. The same would apply for the node interactive repo in terms of re-writing it.

**Comment by connor4312** [comment]
I'd be down for that. Our discord chat syncer system (to be open sourced soon) is actually written in Typescript. As our frontend moves towards Angular 2, we're considering (not yet final by any means) a gradual transition from JavaScript to Typescript. I agree that support for liveloading and other integrations is lacking in this client; that's something I've wanted to address but never had the time to. You're more than welcome to submit PRs for those!

**Comment by ProbablePrime** [comment]
OO go for it. Let me know if you need any information from us that'll help.

**Comment by artdude543** [comment]
I assume you already have a `tslint` file. Would it be possible if I could have a copy of that to stick to the formatting you'd prefer.

**Comment by SimonSchick** [comment]
I do not think we do have one of those yet.

**Comment by artdude543** [comment]
Was just updated that this port is no longer needed. (With more than 40 hours already put into the re-write) So I can shove the code somewhere if you need it or which ever.

**Comment by connor4312** [comment]
I'm not sure what you were updated with, but no plans have changed in regards to porting the client to Typescript.

**Comment by MattJustMatt** [comment]
No plans have changed wrt to Typescript. What was it that indicated otherwise? I can make sure it's fixed. @artdude543

**Comment by artdude543** [comment]
It's been sorted out. More of a miscommunication and a slight over reaction. But the entire client is ported to TS now. Along with the tests are working fine. So I can send an initial PR with the port and then the changes / tweaks which are wanted could be added to the new base code?

**Comment by connor4312** [comment]
Definitely, looking forward to seeing what you have 😄
