### ISSUE TITLE
Chat Socket Quirks

### ISSUE THREAD

**Issue by artdude543** [WatchBeam/beam-client-node#53]
The provided chat wrapper has some issues I've noticed since switching my bot to using it full time for connecting to Beam chats. Here are the two main things I've noticed so far. From testing / playing around with the code.
1. The `boot()` method does not check if it already has a socket active (apart from checking if the var is set) and then registers the event listeners on that socket causing duplicated events to occur. I'd think it might be better to return out of the method if we already have an active socket or return the current instance again. So more events are not registered.
2. When errors are thrown from the socket the "error" itself seems to not being passed on the `emit("error".....` which is odd as it should be from reviewing the code and from local testing the error short message and/or the code should be thrown with the error so developers can debug the error. But the socket does not seem to give you any information on regards to what the error was/is. The only one I've seen is `502` errors and that's it.

I've been playing around with the idea of the client having some more emits when `reconnecting` or debug internal events so it helps with debugging. The reconnection would be nice so we can do a timeout for if the client is going to auto reconnect and if it does not then use our own reconnection code as an example. A nice little addition which could have some benefits in the long run.

**Comment by ProbablePrime** [comment]
thanks for opening an issue about this, was going to ask you to. Easier to track :)

**Comment by artdude543** [comment]
It also seems something odd is going with with sockets being closed / erroring as unknown codes are being sent down. See: ![Error](https://sx.artdude.uk/hotlink-ok/ti53-76969-1473119028.png)

**Comment by Doridian** [comment]
Regarding code 1006:

After some testing with and without CloudFlare in the middle, I was not able to reproduce your issue at all.

I tested various WebSocket servers (the implementations we use) and did anything from soft to hard killing them to graceful termination.
Nothing managed to ever produce any illegal error/status code, only the correct status/close codes.

Neither could I get this to happen on "real" chat or constellation.

**Comment by artdude543** [comment]
Hmm, the problem I have is the bot I run gets this often and all we're using is the ws code provided from this module. I have error logs going way back to last year with the same thing. But it's become more recent lately and as `ws` is not throwing the error correctly causing an uncaught exception. (Yet the module does have the error listener) it's causing issues with me trying to watch connections / reboot when needed. It's a bad guessing game which I've already hit rate limits due to the fact.

**Comment by artdude543** [comment]
What is more concerning to me is that we have `ws` connections to other streaming platforms and never had this issue as the correct codes have always been sent down to the client sockets. So I've isolated this issue to just Beam and possible `ws` not doing something right.

**Comment by ProbablePrime** [comment]
I've updated a related issue with some findings: https://github.com/WatchBeam/carina/issues/6

**Comment by artdude543** [comment]
This is no longer an issue.
